### ISSUE TITLE
Fix failing tests for Cassandra 3.11

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sqlectron-core#69]
Looks like they changed the syntax of error messages between 3.7 and 3.11.  Need to go through and verify what the new behavior is, and make it cross-version compatible so that 3.7 (or 3.0) and 3.11 both pass the test suite.

Error messages from test suite:
```
  1) db
       cassandra
         given is already connected
           .executeQuery
             SELECT
               should execute multiple queries:
     AssertionError: expected 'line 3:18 mismatched input \'select\' expecting EOF (                  select * from users;                  [select]...)' to match /missing EOF at 'select'/
      at Context.<anonymous> (spec/db.spec.js:771:42)
      at Generator.throw (<anonymous>)
      at step (spec/db.spec.js:31:191)
      at /home/runner/work/sqlectron-core/sqlectron-core/spec/db.spec.js:31:402
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) db
       cassandra
         given is already connected
           .executeQuery
             INSERT
               should execute multiple queries:
     AssertionError: expected 'line 5:18 mismatched input \'insert\' expecting EOF (...\'user\', \'user@hotmail.com\', \'123456\');                  [insert]...)' to match /missing EOF at 'insert'/
      at Context.<anonymous> (spec/db.spec.js:847:42)
      at Generator.throw (<anonymous>)
      at step (spec/db.spec.js:31:191)
      at /home/runner/work/sqlectron-core/sqlectron-core/spec/db.spec.js:31:402
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) db
       cassandra
         given is already connected
           .executeQuery
             DELETE
               should execute multiple queries:
     AssertionError: expected 'line 3:18 mismatched input \'delete\' expecting EOF (... where username = \'maxcnunes\';                  [delete]...)' to match /missing EOF at 'delete'/
      at Context.<anonymous> (spec/db.spec.js:919:42)
      at Generator.throw (<anonymous>)
      at step (spec/db.spec.js:31:191)
      at /home/runner/work/sqlectron-core/sqlectron-core/spec/db.spec.js:31:402
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) db
       cassandra
         given is already connected
           .executeQuery
             UPDATE
               should execute multiple queries:
     AssertionError: expected 'line 3:18 mismatched input \'update\' expecting EOF (... where username = \'maxcnunes\';                  [update]...)' to match /missing EOF at 'update'/
      at Context.<anonymous> (spec/db.spec.js:991:42)
      at Generator.throw (<anonymous>)
      at step (spec/db.spec.js:31:191)
      at /home/runner/work/sqlectron-core/sqlectron-core/spec/db.spec.js:31:402
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by MasterOdin** [comment]
Done in c801131813cf0c7c7dd3736ecaf65eb13baf1abf
